### ISSUE TITLE
Logo Design Contribution

### ISSUE THREAD

**Issue by ihtiht** [x3388638/LANChat#6]
Hi,

 I am a graphic designer. I contribute to open source projects by making designs. At the same time I am creating a portfolio. You can look at my previous studies from my profile. I noticed that LANChat has not yet got a logo. If you like, I can contribute by designing a logo.

**Comment by x3388638** [comment]
@ihtiht sounds great!
I have took a look for some of your previous design, and all of them are awesome!
How can I help you to design the logo?

The main ideas of LANChat are:
1. A chat app that can be used offline, which means that users, who connect to the same WiFi, can send and receive messages no matter the Internet is in service or not.
2. Send emergency message: If there is something urgent like trapped in an earthquake, and the Internet is down, user can use this app to send emergency message for help.
3. It's decentralized (there isn't a central server in the system structure)
4. It's goal is to be a "secure" chat app, which can be used for a enterprise secret meeting.
5. QR Code plays an important role in the process of joining a group.

**Comment by ihtiht** [comment]
This informationsis excellent. With the help of these, I will design something and present it to you. 


Wait for me...

**Comment by x3388638** [comment]
@ihtiht 
💪Thanks a lot!

**Comment by ihtiht** [comment]
Hi, I made the design. 

![lanchat](https://user-images.githubusercontent.com/36369736/41867535-0c6d3d7a-78bc-11e8-81e0-e020d8c52ff0.jpg)

I think LANChat's most striking feature is the lack of a center. So, I emphasized decentralization in design. I also made a connection between them. And I made different designs with the item that represents the message. Do you like any of these designs? Which one is nice? I do not need to say that I can change the design according to your wishes. (By the way, my favor is 1st design. I like simplicity.)

**Comment by x3388638** [comment]
@ihtiht 
Really nice!
I like the 2nd one.

**Comment by ihtiht** [comment]
In which format do you want the files?

**Comment by x3388638** [comment]
@ihtiht I think PNG is ok.

**Comment by ihtiht** [comment]
I sent a PR with the necessary files. https://github.com/x3388638/LANChat/pull/7

**Comment by x3388638** [comment]
merged!
